### ISSUE TITLE
AttributeError after upgrading to line-profiler 4.0.0 from 3.5.1

### ISSUE THREAD

**Issue by Mogost** [pyutils/line_profiler#183]
I do not see anything in changelog that may cause this.
```
Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/v_ver/lib/python3.8/site-packages/django/contrib/staticfiles/handlers.py", line 76, in __call__
    return self.application(environ, start_response)
  File "/Users/user/.pyenv/versions/v_ver/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
    response = self.get_response(request)
  File "/Users/user/.pyenv/versions/v_ver/lib/python3.8/site-packages/django/core/handlers/base.py", line 130, in get_response
    response = self._middleware_chain(request)
  File "/Users/user/.pyenv/versions/v_ver/lib/python3.8/site-packages/django/core/handlers/exception.py", line 49, in inner
    response = response_for_exception(request, exc)
  File "/Users/user/.pyenv/versions/v_ver/lib/python3.8/site-packages/django/core/handlers/exception.py", line 114, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Users/user/.pyenv/versions/v_ver/lib/python3.8/site-packages/django/core/handlers/exception.py", line 149, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/user/.pyenv/versions/v_ver/lib/python3.8/site-packages/django_extensions/management/technical_response.py", line 41, in null_technical_500_response
    raise exc_value
  File "/Users/user/.pyenv/versions/v_ver/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/user/.pyenv/versions/v_ver/lib/python3.8/site-packages/debug_toolbar/middleware.py", line 58, in __call__
    response = toolbar.process_request(request)
  File "/Users/user/.pyenv/versions/v_ver/lib/python3.8/site-packages/debug_toolbar/panels/__init__.py", line 206, in process_request
    return self.get_response(request)
  File "/Users/user/.pyenv/versions/v_ver/lib/python3.8/site-packages/debug_toolbar/panels/__init__.py", line 206, in process_request
    return self.get_response(request)
  File "/Users/user/.pyenv/versions/v_ver/lib/python3.8/site-packages/debug_toolbar/panels/timer.py", line 65, in process_request
    return super().process_request(request)
  File "/Users/user/.pyenv/versions/v_ver/lib/python3.8/site-packages/debug_toolbar/panels/__init__.py", line 206, in process_request
    return self.get_response(request)
  File "/Users/user/.pyenv/versions/v_ver/lib/python3.8/site-packages/debug_toolbar/panels/__init__.py", line 206, in process_request
    return self.get_response(request)
  File "/Users/user/.pyenv/versions/v_ver/lib/python3.8/site-packages/debug_toolbar/panels/headers.py", line 46, in process_request
    return super().process_request(request)
  File "/Users/user/.pyenv/versions/v_ver/lib/python3.8/site-packages/debug_toolbar/panels/__init__.py", line 206, in process_request
    return self.get_response(request)
  File "/Users/user/.pyenv/versions/v_ver/lib/python3.8/site-packages/debug_toolbar/panels/__init__.py", line 206, in process_request
    return self.get_response(request)
  File "/Users/user/.pyenv/versions/v_ver/lib/python3.8/site-packages/debug_toolbar/panels/__init__.py", line 206, in process_request
    return self.get_response(request)
  [Previous line repeated 1 more time]
  File "/Users/user/.pyenv/versions/v_ver/lib/python3.8/site-packages/template_profiler_panel/panels/template.py", line 250, in process_request
    response = super(TemplateProfilerPanel, self).process_request(request)
  File "/Users/user/.pyenv/versions/v_ver/lib/python3.8/site-packages/debug_toolbar/panels/__init__.py", line 206, in process_request
    return self.get_response(request)
  File "/Users/user/.pyenv/versions/v_ver/lib/python3.8/site-packages/debug_toolbar/panels/staticfiles.py", line 116, in process_request
    return super().process_request(request)
  File "/Users/user/.pyenv/versions/v_ver/lib/python3.8/site-packages/debug_toolbar/panels/__init__.py", line 206, in process_request
    return self.get_response(request)
  File "/Users/user/.pyenv/versions/v_ver/lib/python3.8/site-packages/debug_toolbar/panels/__init__.py", line 206, in process_request
    return self.get_response(request)
  File "/Users/user/.pyenv/versions/v_ver/lib/python3.8/site-packages/debug_toolbar/panels/__init__.py", line 206, in process_request
    return self.get_response(request)
  File "/Users/user/.pyenv/versions/v_ver/lib/python3.8/site-packages/debug_toolbar/panels/logging.py", line 95, in process_request
    return super().process_request(request)
  File "/Users/user/.pyenv/versions/v_ver/lib/python3.8/site-packages/debug_toolbar/panels/__init__.py", line 206, in process_request
    return self.get_response(request)
  File "/Users/user/.pyenv/versions/v_ver/lib/python3.8/site-packages/debug_toolbar_line_profiler/panel.py", line 206, in process_request
    self._unwrap_closure_and_profile(self.view_func)
  File "/Users/user/.pyenv/versions/v_ver/lib/python3.8/site-packages/debug_toolbar_line_profiler/panel.py", line 198, in _unwrap_closure_and_profile
    self._unwrap_closure_and_profile(value)
  File "/Users/user/.pyenv/versions/v_ver/lib/python3.8/site-packages/debug_toolbar_line_profiler/panel.py", line 198, in _unwrap_closure_and_profile
    self._unwrap_closure_and_profile(value)
  File "/Users/user/.pyenv/versions/v_ver/lib/python3.8/site-packages/debug_toolbar_line_profiler/panel.py", line 179, in _unwrap_closure_and_profile
    self.line_profiler.add_function(func)
  File "line_profiler/_line_profiler.pyx", line 196, in line_profiler._line_profiler.LineProfiler.add_function
  File "line_profiler/_line_profiler.pyx", line 219, in line_profiler._line_profiler.LineProfiler.add_function
AttributeError: 'method' object has no attribute '__code__'
```
Connected with https://github.com/mikekeda/django-debug-toolbar-line-profiler/issues/9

**Comment by Erotemic** [comment]
@Theelx can you take a look at this?

**Comment by Theelx** [comment]
Ah, I'll do some debugging now.

**Comment by Theelx** [comment]
@Mogost Can you provide some sample code to trigger this issue? I don't currently have my computer with me (I'm on my Github app now) so it'd help if I could see the code that's causing the issue and think about a solution while I'm on the move.

**Comment by Theelx** [comment]
I'm on my computer now, and when I add the `@profile` decorator to a method in a class, or when I create an instance of the `LineProfiler` class and call `LineProfiler.add_function` on the method, it works fine on CPython 3.8.13 and 3.9.13 (in pyenv). I see you're using 3.8, so that's interesting.

**Comment by Theelx** [comment]
@Mogost Can you try using the `Test.method = profile(Test.method)` trick that I mentioned above, and see if it works?

**Comment by Mogost** [comment]
```
Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/var/lib/python3.8/site-packages/django/contrib/staticfiles/handlers.py", line 76, in __call__
    return self.application(environ, start_response)
  File "/Users/user/.pyenv/versions/var/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
    response = self.get_response(request)
  File "/Users/user/.pyenv/versions/var/lib/python3.8/site-packages/django/core/handlers/base.py", line 130, in get_response
    response = self._middleware_chain(request)
  File "/Users/user/.pyenv/versions/var/lib/python3.8/site-packages/django/core/handlers/exception.py", line 49, in inner
    response = response_for_exception(request, exc)
  File "/Users/user/.pyenv/versions/var/lib/python3.8/site-packages/django/core/handlers/exception.py", line 114, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Users/user/.pyenv/versions/var/lib/python3.8/site-packages/django/core/handlers/exception.py", line 149, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/user/.pyenv/versions/var/lib/python3.8/site-packages/django_extensions/management/technical_response.py", line 41, in null_technical_500_response
    raise exc_value
  File "/Users/user/.pyenv/versions/var/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/user/.pyenv/versions/var/lib/python3.8/site-packages/debug_toolbar/middleware.py", line 58, in __call__
    response = toolbar.process_request(request)
  File "/Users/user/.pyenv/versions/var/lib/python3.8/site-packages/debug_toolbar/panels/__init__.py", line 206, in process_request
    return self.get_response(request)
  File "/Users/user/.pyenv/versions/var/lib/python3.8/site-packages/debug_toolbar/panels/__init__.py", line 206, in process_request
    return self.get_response(request)
  File "/Users/user/.pyenv/versions/var/lib/python3.8/site-packages/debug_toolbar/panels/timer.py", line 65, in process_request
    return super().process_request(request)
  File "/Users/user/.pyenv/versions/var/lib/python3.8/site-packages/debug_toolbar/panels/__init__.py", line 206, in process_request
    return self.get_response(request)
  File "/Users/user/.pyenv/versions/var/lib/python3.8/site-packages/debug_toolbar/panels/__init__.py", line 206, in process_request
    return self.get_response(request)
  File "/Users/user/.pyenv/versions/var/lib/python3.8/site-packages/debug_toolbar/panels/headers.py", line 46, in process_request
    return super().process_request(request)
  File "/Users/user/.pyenv/versions/var/lib/python3.8/site-packages/debug_toolbar/panels/__init__.py", line 206, in process_request
    return self.get_response(request)
  File "/Users/user/.pyenv/versions/var/lib/python3.8/site-packages/debug_toolbar/panels/__init__.py", line 206, in process_request
    return self.get_response(request)
  File "/Users/user/.pyenv/versions/var/lib/python3.8/site-packages/debug_toolbar/panels/__init__.py", line 206, in process_request
    return self.get_response(request)
  [Previous line repeated 1 more time]
  File "/Users/user/.pyenv/versions/var/lib/python3.8/site-packages/template_profiler_panel/panels/template.py", line 250, in process_request
    response = super(TemplateProfilerPanel, self).process_request(request)
  File "/Users/user/.pyenv/versions/var/lib/python3.8/site-packages/debug_toolbar/panels/__init__.py", line 206, in process_request
    return self.get_response(request)
  File "/Users/user/.pyenv/versions/var/lib/python3.8/site-packages/debug_toolbar/panels/staticfiles.py", line 116, in process_request
    return super().process_request(request)
  File "/Users/user/.pyenv/versions/var/lib/python3.8/site-packages/debug_toolbar/panels/__init__.py", line 206, in process_request
    return self.get_response(request)
  File "/Users/user/.pyenv/versions/var/lib/python3.8/site-packages/debug_toolbar/panels/__init__.py", line 206, in process_request
    return self.get_response(request)
  File "/Users/user/.pyenv/versions/var/lib/python3.8/site-packages/debug_toolbar/panels/__init__.py", line 206, in process_request
    return self.get_response(request)
  File "/Users/user/.pyenv/versions/var/lib/python3.8/site-packages/debug_toolbar/panels/logging.py", line 95, in process_request
    return super().process_request(request)
  File "/Users/user/.pyenv/versions/var/lib/python3.8/site-packages/debug_toolbar/panels/__init__.py", line 206, in process_request
    return self.get_response(request)
  File "/Users/user/.pyenv/versions/var/lib/python3.8/site-packages/debug_toolbar_line_profiler/panel.py", line 206, in process_request
    self._unwrap_closure_and_profile(self.view_func)
  File "/Users/user/.pyenv/versions/var/lib/python3.8/site-packages/debug_toolbar_line_profiler/panel.py", line 198, in _unwrap_closure_and_profile
    self._unwrap_closure_and_profile(value)
  File "/Users/user/.pyenv/versions/var/lib/python3.8/site-packages/debug_toolbar_line_profiler/panel.py", line 198, in _unwrap_closure_and_profile
    self._unwrap_closure_and_profile(value)
  File "/Users/user/.pyenv/versions/var/lib/python3.8/site-packages/debug_toolbar_line_profiler/panel.py", line 179, in _unwrap_closure_and_profile
    self.line_profiler.add_function(func)
  File "line_profiler/_line_profiler.pyx", line 196, in line_profiler._line_profiler.LineProfiler.add_function
  File "line_profiler/_line_profiler.pyx", line 221, in line_profiler._line_profiler.LineProfiler.add_function
AttributeError: 'method' object has no attribute '__code__'
```
The problem still persists in 4.0.1

**Comment by Theelx** [comment]
Does using the profile() trick work?

**Comment by cliffckerr** [comment]
I'm also having this issue, although it's hard to reproduce. It caused my GitHub Actions tests to fail:
https://github.com/sciris/sciris/actions/runs/3615173776/jobs/6092102445
```
../sciris/sc_profiling.py:370: in profile
    wrapper = lp(run)
/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/line_profiler/line_profiler.py:53: in __call__
    self.add_function(func)
line_profiler/_line_profiler.pyx:196: in line_profiler._line_profiler.LineProfiler.add_function
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   AttributeError: 'method' object has no attribute '__code__'

line_profiler/_line_profiler.pyx:221: AttributeError
```

This use case here wraps `LineProfiler` by calling `LineProfiler.add_function()`:
https://github.com/sciris/sciris/blob/v2.0.4/sciris/sc_profiling.py#L365

What's weird is that I can't reproduce this bug locally -- I have a fresh `conda` environment with everything seemingly the same as on GitHub, but the test passes.

**Comment by cliffckerr** [comment]
I'm not very experienced reading Cython code, so this could be a red herring, but the change I saw that seems most likely to be related to this bug is the change in the old version of the code from
```py
<object>py_frame.f_code
```
being used to initialize the `LineTiming` class, to
```py
code = func.__code__
```
being used in the new `_code_replace()` instead.

**Comment by Theelx** [comment]
I'm looking into this now with your new information. Thanks for reporting this!

**Comment by Theelx** [comment]
@cliffckerr It should be fixed in #191. Can you confirm that https://github.com/Theelx/sciris/actions/runs/3616146614 fixes the error and looks good before I ask @Erotemic to merge my PR?

**Comment by cliffckerr** [comment]
Yes that looks great -- thank you so much for the fast response @Theelx !

**Comment by Mogost** [comment]
Fixed by #191
