### ISSUE TITLE
No __version__ attribute

### ISSUE THREAD

**Issue by durden** [pyutils/line_profiler#9]
I think something is wrong with the packaging of 3.0.0 and 3.0.1. I'm seeing the following error when trying to see the final results. This works with version 2.1.2.

```
(py27-macos) [~/Documents/work/engine] $ python -m line_profiler cli.py.lprof
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/durden/Documents/work/engine/.tox/py27-macos/lib/python2.7/site-packages/line_profiler/__main__.py", line 4, in <module>
    main()
  File "/Users/durden/Documents/work/engine/.tox/py27-macos/lib/python2.7/site-packages/line_profiler/line_profiler.py", line 421, in main
    version=line_profiler.__version__)
AttributeError: 'module' object has no attribute '__version__'
```

**Comment by durden** [comment]
Could also be some ordering issue when trying to import the `line_profiler/__init__.py` from `line_profiler/line_profiler.py`.

**Comment by Erotemic** [comment]
@durden I'm currently looking into the issue. I want to be 100% sure that the new version is backwards compatible with 2.1.2. 

I've written a test here: https://github.com/pyutils/line_profiler/pull/10 which attempts to replicate the issue. It looks like its a Python 2 problem. Currently checking to see if I can fix it. 

----

Also FWIW, I see that you're running line_profiler using the two-step method. IMHO two things is way too much work. I've built a wrapper around lineprofiler in my `xdev` package where you only need run one thing to get line-profiling results. 

For example say you have a function you want to profile, import `xdev` and decorate it with `@xdev.profile`. 

```python
import xdev
@xdev.profile
def my_inefficient_function():
    a = 0
    for i in range(10):
        a += i
        for j in range(10):
            a += j

if __name__ == '__main__':
    my_inefficient_function()

```

Then just run your script with `--profile` in the command line args and at the end of your script `xdev` will dump all the profiling information to a file as well as a report to stdout.

**Comment by Erotemic** [comment]
@durden, I believe the issue is fixed in version `3.0.2` please `pip install line_profiler -U` and see if your issue is resolved.

**Comment by durden** [comment]
@Erotemic Thanks for quick fix. I verified it works in Python 2.7.

I agree having to run `line_profiler` with the 2 step process is annoying. I didn't know there was another way. Maybe something could be written about your `xdev` package in the README or that behavior could be integrated into this fork of line_profiler?

**Comment by Erotemic** [comment]
Its possible that I might seek to port what I wrote in xdev to this repo, but that would be a new feature, so I'd want to make sure that existing functionality is 100% stable before I do any of that.
