### PR TITLE
Fix build on Python 3.14 + GCC 15 by isolating internal C headers

### PR DESCRIPTION
**Pull request by jerome-benoit**
Python 3.14 introduces C++ templates in `dynamic_annotations.h` (included via `internal/pycore_interp.h`). This caused compilation errors ("template with C linkage") because these headers were included inside `extern "C"` blocks in `c_trace_callbacks.h`, which is required for Cython/C++ compatibility.

This commit refactors the code to separate the interface from the implementation details:

- Moved internal Python header includes and compatibility macros (for `_PyGC_FINALIZED`, `HAVE_STD_ATOMIC`, etc.) from `c_trace_callbacks.h` to `c_trace_callbacks.c`.
- `c_trace_callbacks.c` is now compiled asFix build on Python 3.14 by isolating internal C headers

Python 3.14 introduces C++ templates in `dynamic_annotations.h` (included via `internal/pycore_interp.h`). This caused compilation errors ("template with C linkage") because these headers were included inside `extern "C"` blocks in `c_trace_callbacks.h`, which is required for Cython/C++ compatibility.

This commit refactors the code to separate the interface from the implementation details:

- Moved internal Python header includes and compatibility macros (for `_PyGC_FINALIZED`, `HAVE_STD_ATOMIC`, etc.) from `c_trace_callbacks.h` to `c_trace_callbacks.c`.
- `c_trace_callbacks.c` is now compiled as

### CODE REVIEW

**Comment by jerome-benoit** [comment]
@Erotemic: I have no clue on why the wheel build is failing on windows, it's a simple code move with trivial c++ guard additions to comply with cpython API changes. No functional changes. 

Without a similar fix, line_profiler cannot be installed on recent distro including python 3.14 as default: fedora 43, ...

**Comment by Erotemic** [comment]
Hmm, looks like the issue is real though. I'm not sure exactly what it is either.

**Comment by lysnikolaou** [comment]
Hey folks! I'm currently trying to figure out what it would take for `line_profiler` to support the free-threaded build of Python 3.14. This problem is blocking me. Could I help move this along?

The CI failure appears to be related to symbol visibility of a couple of `inline` functions. Moving these function from the `.c` file to the header file and defining them with `static inline` ought to fix the issue, I think.

**Comment by Erotemic** [comment]
@lysnikolaou if you want to fork this and submit a PR with your modifications to test them on CI that would help. I have limited ability to look into the issues at the moment, but I'll review code if the dashboards are green.

**Comment by lysnikolaou** [comment]
Sure, I can do that. I didn't want to step on any toes and open a PR before @jerome-benoit has signaled whether they're planning to move this forward.

**Comment by jerome-benoit** [comment]
> Sure, I can do that. I didn't want to step on any toes and open a PR before @jerome-benoit has signaled whether they're planning to move this forward.

I do not have a clue about the build failure on windows. And haven't got the time the setup a windows dev env to dig it further. So please proceed. I guess the build fix will end up being a hack more or less ugly ...

**Comment by lysnikolaou** [comment]
I've opened #412.

**Comment by jerome-benoit** [comment]
Superseded by #412
